name: Syncronize Product version to openjournaltheme site.

on:
  push:
    branches: 
      - 33

jobs:
  curl_to_wordpress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Install xmllint
      run: sudo apt-get install -y libxml2-utils

    - name: Extract version from the version.xml
      id: extract_version
      run: |
        version=$(xmllint --xpath "string(/version/release)" version.xml)
        class=$(xmllint --xpath "string(/version/class)" version.xml)
        product=$(xmllint --xpath "string(/version/application)" version.xml)
        date=$(xmllint --xpath "string(/version/date)" version.xml)
        type=$(xmllint --xpath "string(/version/type)" version.xml)
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "product=$product" >> $GITHUB_OUTPUT
        echo "date=$date" >> $GITHUB_OUTPUT
        echo "type=$type" >> $GITHUB_OUTPUT
        echo "class=$class" >> $GITHUB_OUTPUT
    
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-name@v6

    - name: Construct URL
      id: construct_url
      run: |
        url="https://openjournaltheme.com/wp-json/openjournalvalidation/v3/product/update-version?key=g4Tj9qL2xWz8RkD1s&version=${{ steps.extract_version.outputs.version }}&min_version=${{ steps['branch-name'].outputs.current_branch }}&class=${{ steps.extract_version.outputs.class }}"
        echo "url=$url" >> $GITHUB_OUTPUT

    - name: Curl to WordPress site
      run: |
        curl -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "${{ steps.construct_url.outputs.url }}"


    - name: Echo URL
      run: |
        echo "The URL is: ${{ steps.construct_url.outputs.url }}"